name = "PHCPack"
uuid = "78847b12-ad79-11eb-2f13-bfc10916fd24"
authors = ["Sascha Timme <sascha@timme.xyz>", "Paul Breiding <p.breiding@tu-berlin.de>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
