name = "PHCPack"
uuid = "ced0eddd-41b0-4425-8498-915654d00941"
authors = ["Sascha Timme <sascha@timme.xyz>", "Paul Breiding <pbrdng@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
